### ISSUE TITLE
Redirect URI is always localhost:3000

### ISSUE THREAD

**Issue by bteres** [snowping/meteor.adfs-oauth#2]
Hi,

I have tested this package locally and all seems fine. Now I am going to a live environment and when I change the URL in the client ID on Windows Server, I get an error.

The way I understand it, is that the application is forwarding localhost:3000 to the ADFS server and this is not matching the settings and so it throws an error. How do I get my application running on a server to send its URL as the redirect URI?

Cheers,
Brett

**Comment by snowping** [comment]
Hi,

The redirect URI is setup on your windows server. Just make sure you add the proper adfsclient configuration for your live environment:
`Add-ADFSClient -Name "Meteor Demo App" -ClientId "meteordemoapp" -RedirectUri "https://yourlivesite.com/_oauth/adfsoauth"`

However you always have to make sure that your clientId and resource setting in meteor is aligned with your adfs configuration on windows. 

Does it help?

Cheers, Joël

**Comment by snowping** [comment]
Btw: maybe you have to setup your ROOT_URL env correctly first. see here: https://docs.meteor.com/environment-variables.html#ROOT-URL. The redirect url should be generated based on this env. Not sure about the newest meteor version though.
